// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwyobwmbycyylsebevwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eW9id21ieWN5eWxzZWJldnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzQ4ODIsImV4cCI6MjA2ODE1MDg4Mn0.rdcpHRY5Jvs0npdF6WJ9cN8a15XMAZmZVnHbuc_NbM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});